
export const errorConstants = {
    userRequired:'errors.auth.user_required',
    passwordRequired:'errors.auth.password_required',
    tokenNotSend: 'errors.token.not_send',
    emailNotSend: 'error.email.not_send',
    nameNotSend: 'errors.email.not_send',
    couldNotVerifyToken: 'errors.could.not.verify_token',
    nameRequired: 'errors.auth.name_required',
    nitRequired: 'errors.company.nit_required',
    statusRequired: 'errors.company.status_required',
    platformRequired: 'errors.company.platform_required',
    rutRequired: 'errors.company.rut_required',
    chamberRequired: 'errors.company.chamber_required',
    idRepresentativeRequired: 'errors.company.id_representative_required',
    companyExists: 'errors.company.company_exist',
    serverError: 'errors.server_error',
    idInvalid: 'error.id_invalid',
    descriptionRequired: 'error.description_required',
    imageIsRequired: 'errors.image_is_required',
    shouldSendCodeOrQR: 'errors.should_send_one_qr_or_code',
    typeCouponNotFound: 'errors.type_coupon_not_found',
    categoryCouponNotFound: 'errors.category_coupon_not_found',
    companyCuponeraNotFound: 'errors.company_cuponera_not_found',
    typeCouponAlreadyExists: 'errors.type_coupon_already_exist',
    categoryAlreadyExist: 'erros.categorie_already_exist',
    couponsFound: 'errors.coupons_not_found',
    invalidToken: 'errors.invalid_token',
    userNotFound: 'errors.cuponera.user_not_found',
    actionInvalid: 'errors.action_invalid',
    alreadyIsFeatured: 'errors.already_is_featured',
    notauthorized: 'errors.not_authorized',
    couponNotFound: 'errors.coupon_not_found',
    dateInvalid: 'errors.coupon.date_invalid',
    invalidType: 'errros.type_invalid_input',
    requiredInput: 'errors.input_is_required',
    oneIsRequired: 'errors.at_least_one_fiel_is_required',
    alreadyIsFavorite: 'errors.already_is_favorite',
    unauthorizedUser: 'errors._unauthorized_user',
    missingField:'error_missing_field',
    starDateInvalid: 'errors.startDate.date_invalid',
    fileNotFound: 'errors.cloud.file_not_found',
    invalidFormat: 'errors.cloud.invalid_format',



}