openapi: 3.0.0
info:
  title: GInventaery
  description: GI MicroServicio inventario
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: Users
    description: Rutas para la administración de usuarios
  - name: Category
    description: Rutas para la administración de los categorias
  - name: Products
    description: Rutas para la administración de las productos
paths:
  /auth/login-google:
    post:
      summary: Authenticate with Google
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_token:
                  type: string
      responses:
        '200':
          description: Successful operation
  /auth/validate-token:
    get:
      summary: Validate authentication token
      tags:
        - Users
      responses:
        '200':
          description: Successful operation
  /categories/create:
    post:
      summary: Create a new category
      tags:
        - Category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Successful operation
  /categories/list:
    get:
      summary: Get a list of all categories
      tags:
        - Category
      responses:
        '200':
          description: Successful operation
  /products/create:
    post:
      summary: Create a new product
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                category:
                  type: string
                  format: uuid
                description:
                  type: string
                price:
                  type: number
                amount:
                  type: number
                img:
                  type: string
      responses:
        '200':
          description: Successful operation
  /products/list:
    get:
      summary: Get a list of products
      tags:
        - Products
      responses:
        '200':
          description: Successful operation
  /products/category/{idCategory}:
    get:
      summary: Get a list of products by category
      tags:
        - Products
      parameters:
        - name: idCategory
          in: path
          required: true
          description: ID of the category
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
  /products/update/{productId}:
    get:
      summary: Update a product
      tags:
        - Products
      parameters:
        - name: productId
          in: path
          required: true
          description: ID of the product
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                category:
                  type: string
                  format: uuid
                description:
                  type: string
                price:
                  type: number
                amount:
                  type: number
                img:
                  type: string
      responses:
        '200':
          description: Successful operation
  /products/delete/{productId}:
    get:
      summary: Delete a product
      tags:
        - Products
      parameters:
        - name: productId
          in: path
          required: true
          description: ID of the product
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
  /products/search:
    post:
      summary: Search for products
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: string
                categoryId:
                  type: string
                  format: uuid
      responses:
        '200':
          description: Successful operation