openapi: 3.0.0
info:
  title: Ginventory
  description: Ginventory 
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description:  URL local

paths: 
  /:
  /auth/login-google:
    post:
      summary: Ruta para loguearse con google
      tags: 
        - Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginGoogleSchema'
      responses:
        '200':
          description: Un Json con las caracteristicas de la compañia 